### ISSUE TITLE
I could not login to the site

### ISSUE THREAD

**Issue by manonazari** [mwinteringham/restful-booker-platform#1]
I could not login to the site, what use name and password should I use?
I used admin & password, admin without password. Neither worked.

**Comment by kayyala** [comment]
Me too facing  same issue.. unable to login to console

**Comment by mwinteringham** [comment]
Any chance of a screenshot of the issue?

**Comment by sham332** [comment]
I had a same issue. It was cors issue and node server on auth was blocking it. I found this by looking into firefox console and below was the error

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.99.100:3004/auth. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Run the `docker ls` and get the ip
```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.3   
```
Note down the above IP and add your IP address into cors origin  array object in files(`auth/app.js,hotel/app.js,booking/app.js`) as below

```

var corsOptions = {
  "credentials": true,
  "origin": ['http://localhost:3003', /http:\/\/52.[0-9]*.[0-9]*.[0-9]*:3003/,'http://192.168.99.100:3003']
}
```
This resolved me issue with login, and then further issues with booking and adding hotel

**Comment by mwinteringham** [comment]
So yeah this is because the app is configured to run off localhost since I am using the latest version of Docker for Mac.  I hadn't considered what would happen with Docker Toolbox.

I'll look into how I can add the docker host IP into origin to make it more robust.

**Comment by mwinteringham** [comment]
Merging this issue into larger bucket issue #5
