### ISSUE TITLE
Date Checks are still sensitive to timezones

### ISSUE THREAD

**Issue by cuff-links** [mwinteringham/restful-booker-platform#102]
#50 was an issue opened a while ago where times were off due to me being in EST vs UTC. The test now doesn't use timestamps but uses dates. I just tried to run the suite and still got a failure. I ran the tests at 6:30pm EST which make it either 12:30am I believe. This causes the test to fail because the actual is a day behind the expected.

**Comment by silne30** [comment]
Changed timezone to Ukraine where it's 12:30am and all tests passed. @mwinteringham Hope this helps.

**Comment by mwinteringham** [comment]
@cuff-links would you mind testing this out for me again? I stripped out the offending tests as I'm mocking the DB layer now in better tests.

**Comment by cuff-links** [comment]
This passes now. Awesome job.
