### ISSUE TITLE
No visual distinction between read/unread messages

### ISSUE THREAD

**Issue by alpherogreg** [mwinteringham/restful-booker-platform#110]
The user has no visual cue to distinguish read and unread messages.

<img width="1395" alt="Screen Shot 2019-10-31 at 10 01 14 AM" src="https://user-images.githubusercontent.com/28969173/67898630-88936180-fbc5-11e9-9e4d-c65873e7c4d1.png">

**Comment by mwinteringham** [comment]
Implemented as part of #134
