### ISSUE TITLE
Bad display on mobile about help popup

### ISSUE THREAD

**Issue by bbutel** [mwinteringham/restful-booker-platform#128]
![Screenshot_20200511-074828](https://user-images.githubusercontent.com/58784865/81528058-1feb2580-935c-11ea-8f6b-13402e20d53f.jpg)

Take a look on above picture. Bottons are displayed on the text.

Chrome navigator on htc one

**Comment by mwinteringham** [comment]
RBP doesn't support mobile. But I will be removing the popup soon with a new feature so closing this as it's related to https://github.com/mwinteringham/restful-booker-platform/issues/120
