### ISSUE TITLE
UI Logout does not work

### ISSUE THREAD

**Issue by HilaryGreen** [mwinteringham/restful-booker-platform#143]
Use the admin screen (after login) then press Logout - nothing happens
In F12 network traffcic the call the the /auth/logout API is incorrect (400 bad request) because it does not send the token in the POST body. Looks like the function dologout() is incorrect. As this is not working, the cookie "token" is not deleted you remain logged in.

Would expect after logout  possibly to be returned to the login screen or home page. Certainly not be able to continue using the screen

**Comment by mwinteringham** [comment]
Fixed woop!
