### ISSUE TITLE
Form submission errors

### ISSUE THREAD

**Issue by Rashmi0986** [mwinteringham/restful-booker-platform#147]
In the room blocking form 

if the user submits the Blank form it is good to have the errors shown below the text box or as whole one short message displaying to the user "Please fill in the form " rather showing all error messages in page .

<img width="1035" alt="Error_messaages_updates" src="https://user-images.githubusercontent.com/56731498/97390416-d63ec900-1902-11eb-8c85-465c90b2bc0c.png">

**Comment by mwinteringham** [comment]
Thanks @Rashmi0986 but I shan't be fixing this as it's a not an app breaking issue. The intention for the site is for people to practise testing and this is an excellent example of some great testing.

**Comment by Rashmi0986** [comment]
Thank You Mark .



Thanks ,​
RASHMI BS
​
________________________________
