### ISSUE TITLE
arguments sometimes passed to assertEquals in wrong order

### ISSUE THREAD

**Issue by stansv** [mwinteringham/restful-booker-platform#153]
Hi Mark, I want to share what I've just noticed :)

`org.junit.Assert.assertEquals` accepts `expected` with first arg and `actual` with 2nd one, so

`assertEquals(response.getStatusCode(), 200);`

produces confusing report if test fails. Should be

`assertEquals(200, response.getStatusCode());`

Example: https://github.com/mwinteringham/restful-booker-platform/blob/trunk/booking/src/test/java/com/automationintesting/integration/BookingValidationIT.java#L34

**Comment by mwinteringham** [comment]
Totally busted on this one! Thanks for raising it @stansv, I've updated them now
