### ISSUE TITLE
5. Basic profit reports

### ISSUE THREAD

**Issue by mwinteringham** [mwinteringham/restful-booker-platform#18]
As a B&B owner
I want to see how much each room is making
So I can quickly determine which is the most profitable room

Features:
- All rooms are shown on a graph on X-axis
- Y-axis will show the total of all the booking prices added to together

**Comment by mwinteringham** [comment]
Feature complete

**Comment by jfbookingbug** [comment]
as the rooms are grouped by roomId but labelled by room number, it's possible to add a room that has two uses single/double/twin and for it to appear as the same room in the chart, potentially what would fix this would be to include some of the room details underneath the room number.

**Comment by mwinteringham** [comment]
@jfbookingbug Have/could you raise this as a bug please.
