### ISSUE TITLE
Build failure in restful-booker-platform-assets

### ISSUE THREAD

**Issue by german-chacon** [mwinteringham/restful-booker-platform#207]
I am trying to build in Windows 11 but I am getting the following:

[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for restful-booker-platform 1.5.SNAPSHOT:
[INFO]
[INFO] restful-booker-platform-auth ....................... SUCCESS [ 26.268 s]
[INFO] restful-booker-platform-booking .................... SUCCESS [ 36.724 s]
[INFO] restful-booker-platform-room ....................... SUCCESS [ 32.683 s]
[INFO] restful-booker-platform-report ..................... SUCCESS [ 32.682 s]
[INFO] restful-booker-platform-branding ................... SUCCESS [ 42.264 s]
[INFO] restful-booker-platform-message .................... SUCCESS [ 50.656 s]
[INFO] restful-booker-platform-assets ..................... FAILURE [ 24.975 s]
[INFO] restful-booker-platform ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:06 min
[INFO] Finished at: 2022-08-08T12:34:04+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on projectrestful-booker-platform-assets: There are test failures.
[ERROR]
[ERROR] Please refer to C:\...\restful-booker-platform\assets\api\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :restful-booker-platform-assets

when I check the surefire reports I see:

-------------------------------------------------------------------------------
Test set: com.automationintesting.unit.taskanalysis.ServeContentTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.513 s <<< FAILURE! - in com.automationintesting.unit.taskanalysis.ServeContentTest
checkUiServesStaticContent  Time elapsed: 4.484 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
expected: <<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="google" content="notranslate"/>
    <meta http-equiv="Content-Language" content="en"/>
    <title>Restful-booker-platform demo</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"/>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"/>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <script defer="defer" src="js/main.js"/>
  </head>
  <body>
    <div id="root"/>
  </body>
</html>
> but was: <{
    "timestamp": "2022-08-08T05:34:03.133+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/"
}
>
	at com.automationintesting.unit.taskanalysis.ServeContentTest.checkUiServesStaticContent(ServeContentTest.java:33)

The application tries to start but it gets stuck:

#######################################

File Not Found
**Error: Unable to access jarfile assets/api/target/**
Waiting for RBP to turn on.......................................................
/auth/ ready ....
/report/ ready ....
/room/ ready .
/booking/ ready
/message/ ready
/branding/ ready ................................................................................................../...

What could be the issue?

**Comment by mwinteringham** [comment]
Hi @german-chacon it's been a while but are you able to provide the full build log so I can debug the issue?

**Comment by german-chacon** [comment]
Hi @mwinteringham this is what I could get.

[build_log.txt](https://github.com/mwinteringham/restful-booker-platform/files/9502691/build_log.txt)

Let me know if this helps.

**Comment by mwinteringham** [comment]
Hi @german-chacon I only got a partial build log. Could you run the build again using the command `build_locally.cmd > build.log`

**Comment by german-chacon** [comment]
@mwinteringham here you go
[build.log](https://github.com/mwinteringham/restful-booker-platform/files/9554243/build.log)

**Comment by mwinteringham** [comment]
Thanks for that @german-chacon it appears the frontend isn't building properly but the logs aren't showing why.

Could you go into the assets/js and run `npm run build` and send me the output.

**Comment by german-chacon** [comment]
@mwinteringham I just run it, but only got this:

λ npm run build

> ui@1.5.0 build
> webpack --mode=production

'webpack' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mwinteringham** [comment]
@german-chacon try running `npm install -g webpack` then run it again and see what happens

**Comment by german-chacon** [comment]
@mwinteringham I run "npm install -g webpack" and then tried to build, but got the same issue

 
[build.log](https://github.com/mwinteringham/restful-booker-platform/files/9645104/build.log)

**Comment by mwinteringham** [comment]
I've just merged some updates to the build process, would you mind pulling down the changes and running again. Should give us a clearer failure message.

**Comment by german-chacon** [comment]
@mwinteringham here is the latest build log

[build.log](https://github.com/mwinteringham/restful-booker-platform/files/9817825/build.log)

**Comment by mwinteringham** [comment]
So it looks like `npm install` is failing when you build the frontend. Could you go into the `assets/js` folder and run `npm install` and see what the error is

**Comment by german-chacon** [comment]
@mwinteringham here is the log when running the command in assets/js
[2022-11-05T05_27_36_013Z-debug-0.log](https://github.com/mwinteringham/restful-booker-platform/files/9943145/2022-11-05T05_27_36_013Z-debug-0.log)

**Comment by mwinteringham** [comment]
Ok so this looks like an issue in terms of how your machine is configured. The error below shows that NodeJS is asking for the Desktop development with C++ add on of Visual Studio is installed. I must say that it's not an error I have come across, but it is not related to RBP:

> 1442 error gyp verb find VS msvs_version not set from command line or npm config
> 1442 error gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
> 1442 error gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
> 1442 error gyp verb find VS looking for Visual Studio 2015
> 1442 error gyp verb find VS - not found
> 1442 error gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
> 1442 error gyp ERR! find VS 
> 1442 error gyp ERR! find VS msvs_version not set from command line or npm config
> 1442 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> 1442 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
> 1442 error gyp ERR! find VS looking for Visual Studio 2015
> 1442 error gyp ERR! find VS - not found
> 1442 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> 1442 error gyp ERR! find VS 
> 1442 error gyp ERR! find VS **************************************************************
> 1442 error gyp ERR! find VS You need to install the latest version of Visual Studio
> 1442 error gyp ERR! find VS including the "Desktop development with C++" workload.
> 1442 error gyp ERR! find VS For more information consult the documentation at:
> 1442 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> 1442 error gyp ERR! find VS **************************************************************
> 1442 error gyp ERR! find VS

**Comment by karunakaran1983** [comment]
@german-chacon 
I faced the same issue which you faced and it got fixed when I uninstall and reinstall the versions given in Requirements part of Read.md. Please do check if this info helps to resolve your issue. Thanks

RBP is currently known to work with the following requirements:

JDK 15.0.2 or higher (Tested with JDK 18)
Maven 3.6.3
Node 16.15.1
NPM 8.11.0

**Comment by mwinteringham** [comment]
I'm closing this issue as it's not related to RBP. But feel free to comment @german-chacon if you do run into more issues.

**Comment by BenjaminOsei** [comment]
Hi @german-chacon, have you managed to get the issue resolved? If so, could you share what worked for you?
