### ISSUE TITLE
auth_controller /auth/login not return a token 

### ISSUE THREAD

**Issue by copyleftdev** [mwinteringham/restful-booker-platform#212]
per swagger specification upon successful authentication response will yield a token.

Actual Behavior:
returns an empty body with status code 200

Steps to Reproduce:
```
curl --location --request POST 'https://automationintesting.online/auth/login' \
--header 'accept: */*' \
--header 'Referer;' \
--header 'Content-Type: application/json' \
--data-raw '{
  "username": "admin",
  "password": "password"
}'

```
Observe response body does not yield a token

**Comment by mwinteringham** [comment]
The token is returned in the response headers now. Inspect it for a `Set-Cookie` header and you'll find the token.
