### ISSUE TITLE
Inconsistencies with API specification

### ISSUE THREAD

**Issue by apicarve** [mwinteringham/restful-booker-platform#223]
Hello, we are building a research tool to generate API test suites and API specification automatically using UI test suites. When we compared the API specification we generate with the specification provided along with the web application, we found a few inconsistencies. Would you consider this to be a problem with specification or with the application?

Here are the API endpoints for which the server provided a 2xx or a 3xx status but the specification does not include them. 

```
                        "/room-options",
			"/room-head",
			"/report/room/{room}-options",
			"/report/room/{room}-head",
			"/branding-options",
			"/branding-head",
			"/message/count-options",
			"/message/count-head",
			"/report-delete",
			"/report-options",
			"/report-head",
			"/message/{message}-options",
			"/message/{message}-head",
			"/room/{room}-options",
			"/room/{room}-head",
			"/message-options",
			"/message-head"
```

For example `/report-delete` means that we tried the HTTP request `DELETE` on the API endpoint `/report` and received a status 302 from the server but there is no corresponding operation defined in the specification.

**Comment by mwinteringham** [comment]
I'm not sure I totally follow how you generated that list of endpoints but they are not ones that I have explicitly added to RBP. Looking at your example:

> For example /report-delete means that we tried the HTTP request DELETE on the API endpoint /report and received a status 302 from the server but there is no corresponding operation defined in the specification.

I would expect you would get a 302 because you should be calling `/report/` and not `/report`
