### ISSUE TITLE
[BUG] Preserved room details when creating rooms

### ISSUE THREAD

**Issue by annanklv** [mwinteringham/restful-booker-platform#251]
**Pre-conditions:**

User is logged in.

**Steps to reproduce:**

1. Go to the Rooms page.
2. Create a room with selected room details (e.g. TV and WiFi).

**Expected result:**

None of the checkboxes in the new room row are selected.

**Actual result:**

Previously selected checkboxes remain selected in the new room row.

**Comment by mwinteringham** [comment]
Hi @annanklv 

Thanks for raising this. As RBP is a platform for helping people practise testing, the application is intentionally left with bugs within it to help both those who want to practise automation and exploratory testing. I commend you on finding these bugs, but they will not be fixed. So I'll be closing this and the other bugs you've raised.

I'm replying to this specific bug you've raised, but the point applies to all the bugs you have found.
