### ISSUE TITLE
Website not loading 

### ISSUE THREAD

**Issue by maile0** [mwinteringham/restful-booker-platform#252]
Hey, they main page automationtesting.online does not load anymore. It’s a blank page with no errors. What’s going on? I see other people are complaining too.

**Comment by betterversion** [comment]
Looks like this project abandoned. Going to return the book

**Comment by mwinteringham** [comment]
Hi gents,

I've not been able to get to this last week, but I have picked it up tonight and given the site some resources. I've also seen issues with Cloudflare earlier last week appearing that might have impacted the site.

Could you try again and see if you can access it now?

**Comment by betterversion** [comment]
Resolved. Thanks
