### ISSUE TITLE
Build fails - NPM Install Error 

### ISSUE THREAD

**Issue by betterversion** [mwinteringham/restful-booker-platform#253]
![image](https://github.com/mwinteringham/restful-booker-platform/assets/23748065/a6a14fa4-5c99-4962-b7c3-62c5868421dd)

**Comment by mwinteringham** [comment]
Hi,

Are you able to go into `assets/js` and run `npm install` followed by `npm build` and let me know what errors you get? Post the logs in here and I'll see what is going on.

**Comment by tuirgin** [comment]
I was running into similar issues on Win11.  node-gyp wasn't successfully finding needed VisualStudio dependencies. I switched over to WSL, which was painless.
