### ISSUE TITLE
Swagger UI pages yield 404

### ISSUE THREAD

**Issue by cdw-dina** [mwinteringham/restful-booker-platform#254]
Both on local build and the https://automationintesting.online/ site as referenced by the book.

## Local

- http://localhost:3001/room/swagger-ui/index.html
- http://localhost:3000/booking/swagger-ui/index.html
- http://localhost:3004/auth/swagger-ui/index.html
- http://localhost:3002/branding/swagger-ui/index.html
- http://localhost:3006/message/swagger-ui/index.html
- http://localhost:3005/report/swagger-ui/index.html

## Book Reference

- http://mng.bz/44dw ➔ https://automationintesting.online/room/swagger-ui/index.html

**Comment by mwinteringham** [comment]
This is due to springdoc v1 not supporting spring boot 3. I need to update each service to use the following:

```
   <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.6.0</version>
   </dependency>
```

Leaving as a to do note

**Comment by mwinteringham** [comment]
Dependencies have been updated. @cdw-dina if you download the latest code you should see the swagger docs now. I am deploying the change to the main site once the build has completed.

**Comment by cdw-dina** [comment]
They all look to be working on the https://automationintesting.online/ site which is great. I'm planning to do some casual lunch-and-learn presentations where this will feature. Thank you!
