### ISSUE TITLE
Can't clone repository, so can't read book about API testing

### ISSUE THREAD

**Issue by Neoform1** [mwinteringham/restful-booker-platform#257]
Cloning into 'C:\Users\user\Documents\GitHub\restful-booker-platform'...
remote: Enumerating objects: 10428, done.        
remote: Counting objects: 100% (920/920), done.        
remote: Compressing objects: 100% (174/174), done.        
error: RPC failed; curl 56 Recv failure: Connection was reset
error: 1012 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by mwinteringham** [comment]
Hi,

Unfortunately this will be an issue with Git and GitHub rather than this codebase.

I'd suggest taking a look at this SO article:

https://stackoverflow.com/questions/75525749/how-to-fix-this-error-rpc-failed-curl-56-recv-failure-connection-was-reset
