### ISSUE TITLE
Initialisation fails when Timezone not set to UK timezones

### ISSUE THREAD

**Issue by devidcillo** [mwinteringham/restful-booker-platform#33]
Running the shell script will fail if the system's timezone is set to be outside the UK (eg, if you're from Ecuador)

The script will finish after erroring out, informing that the server's been successfully raised, but the app will be unavailable

**Comment by mwinteringham** [comment]
Looks like the API was translating dates incorrectly if in a timezone outside of ETC. Fixed the issue by setting a default timezone for the API.
