### ISSUE TITLE
Not able to run project in Windows

### ISSUE THREAD

**Issue by Ashokkb** [mwinteringham/restful-booker-platform#4]
I have cloned the project and am able to build and run Compose Build and Up commands successfully.  When I try to access with below URL  
http://localhost:3000
http://172.18.0.3:3000
It says "This site can’t be reached localhost refused to connect.
Search Google for localhost 9000
ERR_CONNECTION_REFUSED" 
Not able to access the Application. 
![git_docker](https://cloud.githubusercontent.com/assets/25739898/22878766/e9835d92-f1d2-11e6-8835-ef131c7888b2.JPG)

![git_docker](https://cloud.githubusercontent.com/assets/25739898/22878731/d0d954ae-f1d2-11e6-9e51-7f6da1da4c65.JPG)

**Comment by Ashokkb** [comment]
Same Issue while accessing hosted application using http://localhost:3003.
Cannot proceed further.

**Comment by mwinteringham** [comment]
I assume you a running of Docker toolbox?

**Comment by Ashokkb** [comment]
Its Docker Quickstart Terminal.

**Comment by mwinteringham** [comment]
Merging this issue into larger bucket issue #5
