### ISSUE TITLE
User can't login with enter

### ISSUE THREAD

**Issue by holocen** [mwinteringham/restful-booker-platform#54]
When I type username "admin" and password "password" I can log in only with "Login" button on front page. I want to be logged in with "Enter" key on the keyboard.

![screenshot_1](https://user-images.githubusercontent.com/30656012/50935882-de97ec80-146d-11e9-8126-d8fae9368960.jpg)

**Comment by mwinteringham** [comment]
If I had a pound for everytime this was requested during a training session 😄 

This is not a simple fix and attempts to implement it have really broken the UI. It is something I would like to resolve but for now spending a few extra seconds using the mouse will have to do.
