### ISSUE TITLE
Room details maximum length

### ISSUE THREAD

**Issue by holocen** [mwinteringham/restful-booker-platform#59]
Room details don't have specified maximum length.

![screenshot_12](https://user-images.githubusercontent.com/30656012/50936401-dccf2880-146f-11e9-8693-1c57e0b035d5.jpg)
![screenshot_13](https://user-images.githubusercontent.com/30656012/50936403-dfca1900-146f-11e9-8df3-78a4ff1be94a.jpg)

**Comment by mwinteringham** [comment]
This has been removed. Check out http://automationintesting.online/
