### ISSUE TITLE
Type - bed relation

### ISSUE THREAD

**Issue by holocen** [mwinteringham/restful-booker-platform#60]
Type can only contain the room options Single, Twin, Family, Suite. There must be a correlation between Type and number of beds.

![screenshot_1](https://user-images.githubusercontent.com/30656012/50936593-962dfe00-1470-11e9-9486-82e3c1173167.jpg)

**Comment by mwinteringham** [comment]
A fair point, however, I will likely modify type to be less related to beds (I.E. Standard, Superior, etc.) and that is covered in one of the other issues you have raised so I will close this one down.
