### ISSUE TITLE
Type and Accessible should be drop-downs

### ISSUE THREAD

**Issue by holocen** [mwinteringham/restful-booker-platform#61]
When there are known options, they should be represented as items in the drop-down. This way the user knows what are the options and errors are avoided.

![screenshot_2](https://user-images.githubusercontent.com/30656012/50936742-38e67c80-1471-11e9-8519-44d04eabd739.jpg)

**Comment by mwinteringham** [comment]
This has been fixed. Check out http://automationintesting.online/
