### ISSUE TITLE
No handling for bookings in a deleted room

### ISSUE THREAD

**Issue by alexzahn** [mwinteringham/restful-booker-platform#63]
When you have an booking in a deleted room, when located via search the app fails to load. A GET to `room/[room_id]` returns a 500. An error of `TypeError: Cannot read property 'toString' of undefined` is thrown.

To reproduce:
1. Login as the admin user
2. Either create a room and a booking, then delete the room you created. Alternatively delete room 101 if the default database is currently being used.
3. Using the search feature, search for the name used in the booking which will be visible and then click.

Result:
The above errors are thrown and the app fails to render.

Expected Result:
Either deleting a room should destroy all bookings, or bookings without rooms should error when accessed.

**Comment by mwinteringham** [comment]
Search has been removed in a previous story and bookings are now deleted when rooms are removed
