### ISSUE TITLE
Can duplicate room numbers

### ISSUE THREAD

**Issue by alexzahn** [mwinteringham/restful-booker-platform#64]
There is no uniqueness check on room numbers, and as a result rooms can be created with the same room number.

To Reproduce:
1. Login as the admin
2. Add a room with all valid options and a number of [SOMENUMBER]
3. Add another room with all valid options and a number of [SOMENUMBER]

Result:
Room created

Expected Result:
Should error and enforce room# uniqueness

**Comment by mwinteringham** [comment]
We've discussed this as a feature and decided not to implement as it complicates our training workshop tied to the app.
