### ISSUE TITLE
(Feedback) Preview booking period when hovering over hidden bookings/+ 1 more

### ISSUE THREAD

**Issue by LeticiaFM** [mwinteringham/restful-booker-platform#93]
Having a booking hidden under "+ 1 more" 
And this booking is spanning over few days (also hidden) 
When I click to visualize the hidden booking

**Expected result**:
I would like to be able to see the checking and checkout dates when hovering over it, so i don`t need to open all of them. 

- **App url**: https://team3.automationintesting.online/#/admin/report

**Comment by mwinteringham** [comment]
Decided not to fix as this is a cracking bug for others to find.
